import {
  MyButton,
  MyIcon,
  MyButtonGroup,
  MyCollapse,
  MyCollapseItem,
  MyAlert,
  MyTooltip,
  MyPopConfirm,
  MyDropdown,
  MyDropdownItem,
  MyMessage,
  MyNotification,
  MyInput,
  MyMessageBox,
  MyLoading,
  MySwitch,
  MySelect,
  MyOption,
} from "../components";
import type { Plugin } from "vue";
export default [
  MyButton,
  MyIcon,
  MyButtonGroup,
  MyCollapse,
  MyCollapseItem,
  MyAlert,
  MyTooltip,
  MyPopConfirm,
  MyDropdown,
  MyDropdownItem,
  MyMessage,
  MyNotification,
  MyInput,
  MyMessageBox,
  MyLoading,
  MySwitch,
  MySelect,
  MyOption,
] as Plugin[];
