import {
  MyButton,
  MyIcon,
  MyButtonGroup,
  MyCollapse,
  MyCollapseItem,
  MyAlert,
  MyTooltip,
  MyPopConfirm,
  MyDropdown,
  MyDropdownItem,
  MyMessage,
  MyNotification,
  MyInput,
} from "../components";
import type { Plugin } from "vue";
export default [
  MyButton,
  MyIcon,
  MyButtonGroup,
  MyCollapse,
  MyCollapseItem,
  MyAlert,
  MyTooltip,
  MyPopConfirm,
  MyDropdown,
  MyDropdownItem,
  MyMessage,
  MyNotification,
  MyInput,
] as Plugin[];
